### ISSUE TITLE
LocalNotifications.addOnMessageReceivedCallback not called if app was stopped

### ISSUE THREAD

**Issue by memphisvl** [EddyVerbruggen/nativescript-local-notifications#53] opened 2017-06-19 12:47 UTC
I've been trying to figure out this for quite some time. The plugin works very well, but in this scenario I can't seem to make it work.

1. Schedule a local notification
2. Stop the app (remove from running in Android/iOS)
3. Notification appears in the notification bar (both Android & iOS)
4. Click on notification starts the app
5. LocalNotifications.addOnMessageReceivedCallback is not called

**Versions:**
{N} 2.5.0
Plugin: 1.2.1

```javascript
LocalNotifications.addOnMessageReceivedCallback(data => {
  alert('Id: '+data.id+' Title: '+data.title);
})

// Do I need to register it before or after is ok as well?
platformNativeScriptDynamic().bootstrapModule(AppModule);
```

The scenario I have requires to get notification data in order to show other screen then home.

**Comment by mikraus94** [comment] 2017-07-26 13:41
I have same issue, but only on Android.  On iOS works correctly.

**Comment by ickata** [comment] 2017-07-26 13:52
Hi all,

On my end this is working pretty well. Make sure that you register your onMessageReceived callback as close to the top of your app as possible. If you do this in Page onload for example, or inside some async callback – that might be the cause.

**Comment by mikraus94** [comment] 2017-07-26 13:57
I've registred onMessageReceived by adding local notifications service to providers in app modules and it doesn't work. Have you better idea how to solve it?

**Comment by mikraus94** [comment] 2017-07-26 14:58
Okay, Ive' made change to code. Now, Android works but iOS doesn't work.

**Comment by ickata** [comment] 2017-07-26 15:12
Would you please tell what change you've made?

**Comment by mikraus94** [comment] 2017-07-26 16:59
I've made init method with addOnMessageReceivedCallback in local notification service and call it in first component (app.component.ts)

**Comment by Ericky14** [comment] 2017-09-07 00:17
Are there any updated on this? It works fine on the iOS emulator, but on a real iOS device the receive callback is never called when the app is suspended. But when the app is resumed, the callback from when it was suspended is called.

**Comment by Lacos247** [comment] 2017-12-08 08:47
Same issue here. Tested in Combination with the other firebase plugin Version 5.0.2 and 4.1.2..

**Comment by EddyVerbruggen** [comment] 2018-09-02 20:39
This may be fixed in plugin version 3.0.0 because notifications now use a the new iOS 10 `UNNotificationCenter` framework and the corresponding delegate methods, which seem a little more background-friendly.

**Closed by EddyVerbruggen** 2018-09-02 20:39 UTC

**Comment by StefanNedelchev** [comment] 2021-01-08 12:19
> This may be fixed in plugin version 3.0.0 because notifications now use a the new iOS 10 `UNNotificationCenter` framework and the corresponding delegate methods, which seem a little more background-friendly.

It might be fixed on iOS but it's still broken on Android.
