### ISSUE TITLE
Service exited due to signal: Segmentation fault: 11

### ISSUE THREAD

**Issue by pn222ez** [EddyVerbruggen/nativescript-local-notifications#14] opened 2016-08-23 14:31 UTC
When I run schedule in iOS Simulator v.9.2, the app crashes with error "Service exited due to signal: Segmentation fault: 11".

**Comment by EddyVerbruggen** [comment] 2016-08-23 14:34
That can be caused by many things..

**Comment by pn222ez** [comment] 2016-08-23 14:45
Ok. I cloned the demo app and every time the schedule method is used it crashes.

**Comment by pn222ez** [comment] 2016-08-24 07:12
Worked when I had a value for interval.

**Comment by EddyVerbruggen** [comment] 2016-09-11 15:51
Thanks, fixed in 1.1.2

**Closed by EddyVerbruggen** 2016-09-11 15:51 UTC
